### ISSUE TITLE
RestoreValue != 520.0

### ISSUE THREAD

**Issue by MAGNAT2645** [FlaminSarge/tf_maxspeed_patch#2]
Hi, i have a problem that restorevalue != 520.0 **ALWAYS**. I know that this is first version of patch, but maybe there's a fix?

`L 06/18/2018 - 15:14:41: [tf_maxspeed_patch.smx] Value at (0x5D4309D0) was not expected: (130041585336320.0000) != 520.0. Cowardly refusing to do things.`

After some edit:
```
	iRestoreData = LoadFromAddress(pPatchLocation, NumberType_Int32);
	>> float flRestoreData = float(iRestoreData); <<
	if (>> flRestoreData << != DEFAULT_MAXSPEED) {
		LogError("Value at (0x%.8X) was not expected: (%.4f) != %.1f. Cowardly refusing to do things.", pPatchLocation, >> flRestoreData <<, DEFAULT_MAXSPEED);
		iRestoreData = 0;
		pPatchLocation = Address_Null;
		return;
	}
```

Console prints:
`L 06/18/2018 - 15:39:29: [tf_maxspeed_patch.smx] Value at (0x5D4309D0) was not expected: (1458342784.0000) != 520.0. Cowardly refusing to do things.`

What's the problem?

**Comment by FlaminSarge** [comment]
Gamedata's probably outdated? Dunno.

**Comment by MAGNAT2645** [comment]
From my gamedata:
```
"Games"
{
	"tf"
	{
		"Signatures"
		{
			"CTFGameMovement::ProcessMovement"
			{
				"library"	"server"
				"linux"		"@_ZN15CTFGameMovement15ProcessMovementEP11CBasePlayerP9CMoveData"
				"windows"	"\x55\x8B\xEC\x56\x57\x8B\x7D\x08\x8B\xF1\x85\xFF\x74\x2A\x53"
			}
		}
		"Addresses"
		{
			"CTFGameMovement::ProcessMovement_limit"
			{
				"signature"	"CTFGameMovement::ProcessMovement"
				"windows"
				{
					"offset"	"73"	//0x49
				}
				"linux"
				{
					"offset"	"87"	//0x57
				}
				"mac"
				{
					"offset"	"81"	//0x51
				}
			}
		}
	}
}
```

**Comment by FlaminSarge** [comment]
Wait, why would you edit the iRestoreData to flRestoreData? The purpose of this plugin is to control the max speed value with the cvar, and when the plugin unloads, it should be restored to TF2's default so that once the plugin loads again it can find the proper location for the value...

If you're editing the plugin for some reason, you can't expect it to just work without understanding what the plugin's doing...

**Comment by MAGNAT2645** [comment]
flRestoreData used just like one convertion, so every "view_as float" can be removed.
Plugin don't work even from GitHub.

**Comment by MAGNAT2645** [comment]
I don't know how signatures working but i've found Windows (1) and Linux (2) offsets for **CTFGameMovement::ProcessMovement** from VTable.

**Comment by FlaminSarge** [comment]
float(1) converts '1' to '1.0', which doesn't have the same byte value as '1' and therefore doesn't have the same meaning.
view_as\<float\>(1) is still the same byte value as '1', but the compiler stops complaining about using '1' where it expects a float that's equal to hex 0x00000001 (see https://www.h-schmidt.net/FloatConverter/IEEE754.html )

**Comment by MAGNAT2645** [comment]
Maybe. However it doesn't work in any way.
Also, you have DEFAULT_MAXSPEED which = **520.0**, so iRestoreData must be = 520.0 (just like float(520)). This is my opinion because i use this method for my plugins without any errors.

**Comment by FlaminSarge** [comment]
I don't quite understand what you're asking for here.

I store the byte value of the address that gets edited (0x44020000 == 520.0) into iRestoreData, and then restore that value when the patch is unloaded.

TF2 starts with that value at that location, so if the value that is at that point isn't 520.0 when the plugin loads, then the plugin is looking at the wrong location (gamedata outdated or something). If the starting value isn't 520.0 and the plugin tries to edit it, your server will most likely crash.

**Comment by MAGNAT2645** [comment]
It was a bit off topic. I'm trying to say that iRestoreData != 520.0. Maybe gamedata is a bit old?

**Comment by FlaminSarge** [comment]
I strongly doubt that Valve changed the default value from 520 so probably gamedata. Did you ever mention which OS you were running?

**Comment by MAGNAT2645** [comment]
Test server on Windows 8.1 x64.
Community server on Linux Ubuntu 16.04 x86_64.
I've tested only on Windows.
